### ISSUE TITLE
The difference between paper and code.

### ISSUE THREAD

**Issue by STEVEN-PP** [icantnamemyself/SAN#10]
您好，我在论文中的第3个公式中发现，无论是均值还是标准差的MLP，它们输入之一为 $\overline{x}^i$ ，即输入的规范化，原文公式如下：
<img width="484" alt="屏幕截图 2024-05-28 154646" src="https://github.com/icantnamemyself/SAN/assets/42035521/39ccab18-d9de-45ba-a8ac-6a9ae11e6633">
但在实现code中却是使用原始的输入（非规范化后的），即代码中的input而非norm_input，代码实现如下：
<img width="668" alt="屏幕截图 2024-05-28 155524" src="https://github.com/icantnamemyself/SAN/assets/42035521/427c91dd-bbbc-4376-892e-0abc9bafd9c2">
请问这个地方的出入应遵循哪个版本（paper版本还是code版本）？

**Comment by icantnamemyself** [comment]
感谢你的问题！经过核对，是论文中的描述有问题，输入应为归一化前的原始数据x。请遵循代码实现的版本即可。

**Comment by STEVEN-PP** [comment]
感谢您的反馈！
