### ISSUE TITLE
关于pred_len和period_len的一点问题

### ISSUE THREAD

**Issue by Ycy21253728** [icantnamemyself/SAN#11]
作者大大您好，我自己的数据集是单变量，我将batch_size设置为128，period_len为6，pred_len为1，运行时报了如下错误
![屏幕截图 2024-07-02 115208](https://github.com/icantnamemyself/SAN/assets/74487203/bdca5450-e88f-4ca2-904f-0d4f3c720dc8)
请问是否在进行单变量预测时，pred_len应该是period_len的倍数

**Comment by icantnamemyself** [comment]
目前的代码实现要求pred_len需要是period_len的倍数，不过你也可以稍微修改一下代码的逻辑。如需预测长度为1，可以设置perd_len为6，而后裁剪输出长度至1即可。

**Comment by Ycy21253728** [comment]
感谢您的回复，请问这个period_len对应的是论文中的slicing length吗

**Comment by icantnamemyself** [comment]
是的。

**Comment by Ycy21253728** [comment]
感谢您的耐心回复，祝您科研顺利
