### ISSUE TITLE
Potential Data Leakage

### ISSUE THREAD

**Issue by lvguima** [icantnamemyself/SAN#13]
Thanks for your work!
 I was wondering since the denormalization process involves the predicted statistics (statistics_pred), there is a potential dependency between the TSF model's outputs and the true target values mediated by statistics_pred. This could introduce data leakage, as the model might inadvertently learn to correct or compensate for errors in the predicted statistics based on the true target values during training.
What's your opinion on this issue?

**Comment by icantnamemyself** [comment]
Thanks for your attention to our work and the question!

The TSF models are required to generate forecasting results on target values, and therefore, they are always trained based on the true target values regardless of whether they are using the SAN framework or not. It's conventional that the model learns to correct or compensate for errors in the predicted statistics based on the true target values during training. Moreover, we only use the training subset of a dataset to train the statistic prediction module, ensuring no val/test data leakage will occur.

Hope the comment can address your concern.

**Comment by lvguima** [comment]
You are right. 

I previously thought the statistical model's training was done by first training it completely on the training set and then training the TSF model. If that were the case, there would indeed be a data leakage issue, right?

Thank you for your patient replies!
