### ISSUE TITLE
关于SAN与先前方法观点差异的疑惑

### ISSUE THREAD

**Issue by enjoy66613** [icantnamemyself/SAN#15]
However, these methods typically overlook the distribution discrepancy between the input series and the horizon series, and assume that all time points within the same instance share the same statistical properties, which is too ideal and may lead to suboptimal relative improvements.
 文章的摘要部分指出前面大部分的归一化方法忽略了输入和输出序列之间的分布差异，“并假设同一实例中的所有时间点共享相同的统计属性” 这句话是针对每个输入长度和对应的预测长度 来说的吗   还是说是针对整个数据集某个变量的一整个序列 ?

文章中的 
Statistics Prediction  部分 下面的句子说输入序列的整体均值和 目标序列的均值是极大近似的 ，那不是和前面的方法一样假设同一实例中的所有时间点共享相同的统计属性 了吗 
In detail, we believe that the overall mean of the input sequence ρi = 1 Lin PLin 1 xi ∈ RV ∗1 is a maximum likelihood estimation of the target sequence’s mean ˆ ρi = 1 Lout PLout 1 yi ∈ RV ∗1 since they are temporally related.

**Comment by icantnamemyself** [comment]
感谢您对我们工作的关注。

首先“并假设同一实例中的所有时间点共享相同的统计属性” 这句话是针对每个输入长度和对应的预测长度，详情可参考RevIN[1]的常见实现方式。另外， “输入序列的整体均值和目标序列的均值是极大近似的”一句中主要强调的是均值的**近似性**，而不是等价性。先前的工作假设二者有同样的统计属性；而我们的方法只是基于近似性优化Statistics Prediction Module，最终反归一化所使用的统计属性仍然是学习拟合到的。这是两种方法最明显的区别。
