### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by ownnaruto** [icantnamemyself/SAN#2]
1. 首先，station_pretrain_epoch = 5 是否太小，网络能收敛吗？
2. 没有判断station_model earlystop，导致early stop 失效，station_model将一直训练直到 station_pretrain_epoch 
3. 为什么每次同时调整两个学习率，这样开始训练预测网络的时候，学习率不会过小吗？

**Comment by icantnamemyself** [comment]
感谢您的问题！

1. 由于station_model是一个很小的模型（2层的MLP），所以训练轮次并不需要很高。实验中我们人为固定epoch为5，根据其validation loss观察模型已经基本收敛，而且从最终的forecasting结果来看，增大epoch数并不能带来很明显的收益了。
2. 跟上一条类似的原因，我们在训练station_model时并没有显示地early stop，而只是借用了前人代码中已经存在的`EarlyStopping`工具，以实现`训练5轮，根据validation loss选择最优的station_model`的功能。
3. 在代码中，backbone模型的学习率仅在station_model训练完成之后才会更新。而`exp_main.py`的262到263行本质上是多余代码（这个阶段下station_model已经不进行学习了，改变其优化器学习率没有任何作用）。
