### ISSUE TITLE
关于非平稳的疑问

### ISSUE THREAD

**Issue by ownnaruto** [icantnamemyself/SAN#3]
您好，我对于时间序列非平稳带来的问题一直存在一些疑惑，时间序列非平稳是指序列的统计信息随时间变化，可是这到底是如何影响神经网络模型的预测呢？神经网络预测输入的是历史序列，输出的是未来序列，只要这个映射关系是存在一定规律的，那么神经网络应该就能够在一定程度上学到这种关系，序列的非平稳是如何影响这种映射关系的呢？为什么平稳的序列就一定更好呢？（白噪声也是一种平稳序列，可是却完全无法预测。

**Comment by icantnamemyself** [comment]
您好，根据我浅薄的理解，时间序列的非平稳性可以理解为**输入实例的数据分布随时间会发生变化**，会导致训练集和测试集数据非独立同分布（Non i.i.d.），进而影响了深度学习模型的泛化能力（可以理解为是一种OOD问题）。而在我们文章中采用了和前人类似的建模方法，也即用时序数据**数值的正态分布**来近似代替**输入实例的数据分布**来初步解决这个问题。

平稳性上一定程度影响了数据的可预测性，而关于序列的可预测性，您可以参照这篇文献[1]。

[1] Goerg G. Forecastable component analysis[C]//International conference on machine learning. PMLR, 2013: 64-72.
