### ISSUE TITLE
除了导入数据集路径，并没有对代码进行任何修改，有以下报错

### ISSUE THREAD

**Issue by Lqh3034** [icantnamemyself/SAN#4]
Traceback (most recent call last):
  File "/content/drive/MyDrive/SAN-master/run_longExp.py", line 164, in <module>
    mse, mae = exp.test(setting)
  File "/content/drive/MyDrive/SAN-master/exp/exp_main.py", line 349, in test
    preds = np.array(preds)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (88,) + inhomogeneous part.
请问我该如何修改代码呢

**Comment by icantnamemyself** [comment]
这是numpy版本的问题，可以将349到350行的代码改为
```python
preds = np.array(preds, dtype='object')
trues = np.array(trues, dtype='object')
```

**Comment by Lqh3034** [comment]
> 这是numpy版本的问题，可以将349到350行的代码改为
> 
> ```python
> preds = np.array(preds, dtype='object')
> trues = np.array(trues, dtype='object')
> ```

问题解决了！万分感谢！
