### ISSUE TITLE
SAN和patchTST结合的问题

### ISSUE THREAD

**Issue by Arya87** [icantnamemyself/SAN#7]
由于SAN是非重叠切片，而patchTST是重叠切片，请问在论文中提到的patchTST+SAN的对比实验中各个数据集的切片长度是多少呢？（我基于ETTh1数据集人为设置了12、16、48等多个长度，跑的效果反而比纯patchTST更差了，不确定是代码迁移问题还是切片长度问题），请问对于这个长度设置有做后续研究么？

**Comment by icantnamemyself** [comment]
感谢您的问题！

正如我们论文中提到的，将SAN迁移到PatchTST这种重叠切片型的方法有一定的调参难度。

而对于我们report的结果，具体对应的`period_len`和`station_lr`分别为：
| Dataset     | period_len | station_lr |
| ----------- | ---------- | ---------- |
| Electricity | 24         | 0.0001     |
| Exchange    | 24         | 0.001      |
| Weather     | 12         | 0.0001     |
| ETTh1       | 4          | 0.0001     |
| ETTm2       | 4          | 0.00005    |

同时注意，在进行实验的时候还需要将PatchTST中本来存在的RevIN层给注释掉。

**Comment by Arya87** [comment]
好的，感谢您的回复！
目前还有以下两个问题，：
1、由于时间问题目前先跑了ETTh1，发现精度和原论文结果接近，但效果依旧没有提升。考虑可能是学习率调整的问题，想问一下您针对SAN源代码（line308-325）和patchTST源代码（line326-329）是如何调整的？
2、由于patchTST中未涉及exchange，我基于exchange调整一直无法调整到比较满意的效果（pred_len=336），虽然SAN论文中关于patchTST的pred_len=96，不知您是否方便公布一下基于exchange的patchTST各项参数

**Comment by Arya87** [comment]
![微信图片_20240321204615](https://github.com/icantnamemyself/SAN/assets/86116315/88d73ae6-c575-4963-83e3-3bd373fdc5c1)

**Comment by icantnamemyself** [comment]
1. 首先是学习率调整的问题。在复现PatchTST时，考虑到其有太多的超参数可以调整（包括lr_schedule），这进一步使得SAN的调参变得困难，并且使得baseline之间的对比并不是特别**公平**。因此，我们并没有**完全严格**使用其提供的脚本。具体来说，我们仅使用了推荐的**模型参数和学习率参数**，而epoch数和学习率调整等都是用的原始的默认值。
2. 对于Exchange数据集，考虑到其和ETTh数据集规模近似，我们在复现时直接采用了推荐的ETTh上的超参数。
