### ISSUE TITLE
non_station_factor无效输入问题

### ISSUE THREAD

**Issue by lvguima** [icantnamemyself/SAN#8]
作者你好，我在使用transformer类的方法进行复现时，发现这个non_station_factor似乎并没有输入到encoder内，也没有看到关于non_station_factor的计算方法，是否是我忽略了什么地方呢？
![image](https://github.com/icantnamemyself/SAN/assets/18476346/365339d7-8c4b-4249-b3b4-dc3fc2935fb3)
![image](https://github.com/icantnamemyself/SAN/assets/18476346/2d762a5b-d0bb-4df8-96bf-61ecbbb2d074)
![image](https://github.com/icantnamemyself/SAN/assets/18476346/ea4b11d8-af68-43bc-ac8c-9d6e40686691)

**Comment by icantnamemyself** [comment]
感谢您的问题！

这其实是我们之前在复现Non-stationary Transformer时用到的部分代码，在我们开源的时候没有清理干净。现在最新的代码已经解决了这个问题。
