### ISSUE TITLE
请教下数据集还原的问题

### ISSUE THREAD

**Issue by wangzhe652** [icantnamemyself/SAN#9]
采用该模型做实验时，确实能够很明显地看到时序模型训练的优化，我想请教下，最终的预测结果能否还原到原来的数据维度（因为此前训练时采用了标准化）

**Comment by icantnamemyself** [comment]
当然是可以的。你可以利用数据预处理中`StandardScaler()`类的`inverse_transform`方法完成预测结果的反标准化。

**Comment by wangzhe652** [comment]
刘老师：
&nbsp; &nbsp; &nbsp;您好，我注意到您代码中设置的inverse_transform方法了，但是在exp.test中应用时，没有对应的standardscaler（）类，提示我需要先fit，但是fit在data_loader中，可以请你详细说明下嘛，非常感谢




孙琛恺
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icantnamemyself/SAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icantnamemyself/SAN] 请教下数据集还原的问题 (Issue #9)





 
当然是可以的。你可以利用数据预处理中StandardScaler()类的inverse_transform方法完成预测结果的反标准化。

**Comment by icantnamemyself** [comment]
调用test_data中的scaler即可
